### ISSUE TITLE
Suggest a simple example of change of variables.

### ISSUE THREAD

**Issue by a2468834** [stevengj/Cubature.jl#42] opened 2019-05-03 08:56 UTC
Although there is a [link](https://github.com/stevengj/cubature/blob/master/README.md#infinite-intervals) introducing how to apply change of variables method to compute integrals over infinite or semi-infinite domains, I think taking an example would be more friendly way to explain how to use it. 

> If f(x)=1/(x^2), we could calculate the integral of f(x) over [a, ∞] by hands in advance.
>
> <img src="https://latex.codecogs.com/png.latex?\int_{a}^{\infty}f(x)dx&space;=&space;\int_{a}^{\infty}\frac{1}{x^2}dx&space;=&space;\frac{1}{a}" title="\int_{a}^{\infty}f(x)dx = \int_{a}^{\infty}\frac{1}{x^2}dx = \frac{1}{a}" />

To compute an integral over a semi-infinite interval, you have to perform the change of variables x=a+t/(1-t):

<img src="https://latex.codecogs.com/png.latex?\int_{a}^{\infty}f(x)dx&space;=&space;\int_{0}^{1}f(a&plus;\frac{t}{1-t})\frac{1}{(1-t)^2}dt&space;=&space;\int_{0}^{1}g(a,&space;t)dt" title="\int_{a}^{\infty}f(x)dx = \int_{0}^{1}f(a+\frac{t}{1-t})\frac{1}{(1-t)^2}dt = \int_{0}^{1}g(a, t)dt" />

Now we could turn all of them into Julia script.
```julia
a = 1 # assume that the lower bound of integral is 1.

function f(x)
	return 1/(x^2)
end

function g(a, t)
	return f(a+(t/(1-t)))*(1/(1-t)^2)
end

hquadrature(g, 0, 1)
```
returning `(1.0, 1.1102230246251565e-14)` which are the same as our calculation by hands.

**Comment by a2468834** [comment] 2019-05-04 08:52
Another example about infinite interval integral.

> If f(x)=e^(-x^2), we could calculate the integral of f(x) over [-∞, ∞] by hands in advance.
> 
> <img src="https://latex.codecogs.com/gif.latex?\int_{-\infty}^{\infty}f(x)dx=\int_{-\infty}^{\infty}e^{-x^2}dx=\sqrt{\pi}\approx&space;1.772453850905516\&space;\&space;(by\&space;Gaussian\&space;integral)" title="\int_{-\infty}^{\infty}f(x)dx=\int_{-\infty}^{\infty}e^{-x^2}dx=\sqrt{\pi}\approx 1.772453850905516\ \ (by\ Gaussian\ integral)" />

To compute an integral over a infinite interval, you have to perform the change of variables x=t/(1-t²):

<img src="https://latex.codecogs.com/gif.latex?\int_{-\infty}^{\infty}&space;f(x)dx=\int_{-1}^{1}&space;f\bigg(\frac{t}{1-t^2}\bigg)\frac{1&plus;t^2}{(1-t^2)^2}dt=\int_{-1}^{1}g(t)dt" title="\int_{-\infty}^{\infty} f(x)dx=\int_{-1}^{1} f\bigg(\frac{t}{1-t^2}\bigg)\frac{1+t^2}{(1-t^2)^2}dt=\int_{-1}^{1}g(t)dt" />

Now we could turn all of them into Julia script.

```julia
function f(x)
    return exp(-x^2)
end

function g(t)
    return f(t/(1-t^2))*(1+t^2)/((1-t^2)^2)
end

hquadrature(g, -1, 1)
```

returning (1.772453850905516, 2.95326836403382e-9) which are the same as our calculation by hands.

**Comment by stevengj** [comment] 2019-07-13 17:50
Duplicate of #32

**Closed by stevengj** 2019-07-13 17:50 UTC
